// <auto-generated />
using CV_Project2022.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CV_Project2022.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220815221214_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("CV_Project2022.Data.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CV");
                });

            modelBuilder.Entity("CV_Project2022.Data.CV_SKILL", b =>
                {
                    b.Property<int>("CvId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CvId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CV_SKILL");
                });

            modelBuilder.Entity("CV_Project2022.Data.SKILL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SKILL");
                });

            modelBuilder.Entity("CV_Project2022.Data.CV_SKILL", b =>
                {
                    b.HasOne("CV_Project2022.Data.CV", "CV")
                        .WithMany("CV_SKILL")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Project2022.Data.SKILL", "SKILL")
                        .WithMany("CV_SKILL")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("SKILL");
                });

            modelBuilder.Entity("CV_Project2022.Data.CV", b =>
                {
                    b.Navigation("CV_SKILL");
                });

            modelBuilder.Entity("CV_Project2022.Data.SKILL", b =>
                {
                    b.Navigation("CV_SKILL");
                });
#pragma warning restore 612, 618
        }
    }
}
